apiVersion: v1
kind: Pod
spec:
  containers:
    - name: gradle
      image: gradle:jdk11
      imagePullPolicy: "IfNotPresent"
      command:
        - cat
      tty: true
      volumeMounts:
        - name: gradle-cache
          mountPath: /gradle_local
    - name: docker
      image: docker:latest
      imagePullPolicy: "IfNotPresent"
      command:
        - cat
      tty: true
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
    - name: gradle-cache
      persistentVolumeClaim:
        claimName: jenkins-pv-claim