#Deploy Config
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $IMAGE_NAME-$TAG
  labels:
    app: $IMAGE_NAME-$TAG
spec:
  selector:
    matchLabels:
      app: $IMAGE_NAME-$TAG
  replicas: 1
  template:
    metadata:
      labels:
        app: $IMAGE_NAME-$TAG
    spec:
      containers:
        - name: $IMAGE_NAME-$TAG
          image: $REPOSITORY:$TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          tty: true

---
#Service Config
apiVersion: v1
kind: Service
metadata:
  name: $IMAGE_NAME-svc-$TAG
  labels:
    app: $IMAGE_NAME-$TAG
spec:
  selector:
    app: $IMAGE_NAME-$TAG
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort
