apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
spec:
  selector:
    matchLabels:
      app: hello-world-app
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:service.yaml
        - name: hello-world-app
          image: orelbriga/hello-world-app:$BUILD_NUMBER
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          tty: true
